### ISSUE TITLE
หลังจากติดตั้งแล้ว เมื่อเข้าใช้งาน พบ error ครับ

### ISSUE THREAD

**Issue by xchinjo** [rph-dev/mbs#17]
![image](https://user-images.githubusercontent.com/740332/64902726-b0db0580-d6d6-11e9-9b3f-184dd3a9d0d0.png)

**Comment by kongvut** [comment]
ขอบคุณสำหรับการแจ้งปัญหา Error ครับ
โดยปัญหานี้เกิดจากระบบไม่รับ Permission เขียนไฟล์ได้
เดี๋ยวผมจะลองทดสอบติดตั้งใหม่หมดอีกครั้ง และแก้ไขปัญหาตรงนี้ครับ

เบื้องต้นท่านสามารถแก้ปัญหานี้ได้ด้วยตัวเองดังนี้
docker exec -it mbs-php-fpm sh -c "cd /var/www/mbs-web/ && chmod -R 0775
./storage && chmod -R 0775 ./bootstrap/cache"
หรือ
docker exec -it mbs-php-fpm sh -c "cd /var/www/mbs-web/ && chmod 0775
./storage/storage/logs/laravel.log && chmod -R 0775 ./bootstrap/cache"

ขอบคุณครับ
คงวุฒิ
