### ISSUE TITLE
พบ error หลังจากกรอก user / pass เพื่อ login

### ISSUE THREAD

**Issue by xchinjo** [rph-dev/mbs#18]
สามารถเข้าหน้า login ได้ดล้ว 
![image](https://user-images.githubusercontent.com/740332/64903416-8bec8f80-d6e2-11e9-9327-936393c03890.png)

หลังจากกรอก user / pass 

![image](https://user-images.githubusercontent.com/740332/64903427-afafd580-d6e2-11e9-8575-539338d25148.png)

![image](https://user-images.githubusercontent.com/740332/64904099-06bba780-d6ef-11e9-8fa7-e7d668254f20.png)

docker exec -it mbs-mariadb bash
mysql -uroot

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| test               |
+--------------------+
4 rows in set (0.001 sec)

ไม่มี database ครับ

**Comment by kongvut** [comment]
ผมได้อัพเดท bash script เพิ่มเติมแล้ว ลองแก้ปัญหาดังนี้นะครับ

1. git pull
2. cd docker
3. ./remove-data.sh 
4. ./create.sh
5. ./install.sh

ขอบคุณครับ
คงวุฒิ
