### ISSUE TITLE
ส่ง broadcast Messaging ส่งไม่ได้คะ

### ISSUE THREAD

**Issue by onrampa** [rph-dev/mbs#20]
![bug](https://user-images.githubusercontent.com/21096410/64905148-4473fc80-d6fe-11e9-87b1-59737f373d20.png)
 บุคคลนี้เชื่อมต่อแล้วคะ แต่ไม่สามารถส่ง message ได้
ขอบคุณนะคะ ช่วยแนะนำด้วยคะ

**Comment by kongvut** [comment]
ขอบคุณสำหรับการแจ้งปัญหา Error ครับ
ปัญหาตรงนี้เกิดจาก ปัญหาอะไรสักอย่างกับระบบฐานข้อมูล

รบกวนแอด Line ID: hexdev
ของผมเพื่อคุยและแก้ปัญหานี้เพิ่มเติมครับ

คงวุฒิ

**Comment by kongvut** [comment]
หรือลองแก้ไขปัญหาเบื้องต้น ดังนี้ลองดูก่อนได้ครับ

1. git pull
2. cd docker
3. ./remove-data.sh หรือ remove.sh (หากไม่ต้องการลบข้อมูลออก)
4. ./create.sh
5. ./install.sh

ถ้าติดปัญหาอะไรอื่น ๆ เพิ่มเติม สามารถแอดไลน์มาสอบถามได้นะครับ
คงวุฒิ

**Comment by onrampa** [comment]
ลอง load ไปเทสอีกรอบแล้ว ยังขึ้นเหมือนเดิมคะ  มือใหม่อาจจะทำไม่ครบขั้นตอน เด่วจะลองทำตามวิธีโดยละเอียดอีกทีนะคะ

**Comment by onrampa** [comment]
อ้อ จำเป็นต้องใช้ docker ทำ database mbs_web มั้ยคะ พอดีทำ migration สร้าง db เป็น mysql  ยังใช้ docker ไม่เป็นน่ะคะ แต่รันตัวบอท ได้
![bug2](https://user-images.githubusercontent.com/21096410/64906304-016e5500-d70f-11e9-861d-bc4078abcc1e.png)

**Comment by onrampa** [comment]
สามารถ ส่ง และบันทึกได้แล้วคะ ^^
   private function findLineIdList($groupId){
ยกเลิก        // $groupList = \DB::table('v_mbs_group')->where('group_id', $groupId)->get();
แก้ไขเป็น 
        $groupList = MbsGroup::select(['id', 'group_id', 'contact_id', 'total', 'created_at', 'updated_at'])
            ->selectRaw('substr(`mbs_group`.`contact_id`,1,1) AS `contact_type`, substr(`mbs_group`.`contact_id`,2) AS `contact_only_id`')
            ->where('group_id', $groupId)->get();

**Comment by onrampa** [comment]
เพิ่มเติม   หากสามารถเห็นข้อความจากผู้แชท คุยโต้-ตอบ กันได้จะ perfect สุดๆ คะ
